version: '3.9'

services:
  frontend:
    container_name: frontend
    ports:
      - 5100:5000
    build: ./frontend
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:80

  backend:
    container_name: backend
    ports:
      - 8080:8080
    build: ./backend
    depends_on:
      - redis
      - db
    environment:
      REDIS_HOST: redis
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REQUEST_ORIGIN: http://localhost:80

# exercise 2.4, linking up redis caching
  redis:
    container_name: redis-cache
    image: redis
    restart: unless-stopped

# exercise 2.6, linking up postgres
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: db
    volumes:
      - ./database:/var/lib/postgresql/data

# exercise 2.8 adding nginx
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf





