version: '3.9'

services:
  frontend:
    container_name: frontend
    ports:
      - 5100:5000
    build: ./frontend

  backend:
    container_name: backend
    ports:
      - 8080:8080
    build: ./backend

